var listeVerbe = [
	["be", "was/were", "been", "être"],
	["bear", "bore", "borne", "(sup)porter"],
	["beat", "beat", "beaten", "battre"],
	["become", "became", "become", "devenir"],
	["begin", "began", "begun", "commencer"],
	["bend", "bent", "bent", "(se) courber"],
	["bet", "bet", "bet", "parier"],
	["bite", "bit", "bitten", "mordre"],
	["bleed", "bled", "bled", "saigner"],
	["blow", "blew", "blown", "souffler"],
	["break", "broke", "broken", "casser"],
	["breed", "bred", "bred", "élever"],
	["bring", "brought", "brought", "apporter"],
	["build", "built", "built", "bâtir"],
	["burn", "burnt", "burnt", "brûler*"],
	["burst", "burst", "burst", "éclater"],
	["buy", "bought", "bought", "acheter"],
	["cast", "cast", "cast", "lancer"],
	["catch", "caught", "caught", "attraper"],
	["choose", "chose", "chosen", "choisir"],
	["come", "came", "come", "venir"],
	["cost", "cost", "cost", "coûter"],
	["cut", "cut", "cut", "couper"],
	["deal", "dealt", "dealt", "traiter de"],
	["dig", "dug", "dug", "creuser"],
	["do", "did", "done", "faire"],
	["draw", "drew", "drawn", "tirer/dessiner"],
	["dream", "dreamt", "dreamt", "rêver*"],
	["drink", "drank", "drunk", "boire"],
	["drive", "drove", "driven", "conduire"],
	["eat", "ate", "eaten", "manger"],
	["fall", "fell", "fallen", "tomber"],
	["feed", "fed", "fed", "nourrir"],
	["feel", "felt", "felt", "(res)sentir"],
	["fight", "fought", "fought", "se battre"],
	["find", "found", "found", "trouver"],
	["fly", "flew", "flown", "voler"],
	["forbid", "forbade", "forbidden", "interdire"],
	["forget", "forgot", "forgotten", "oublier"],
	["forgive", "forgave", "forgiven", "pardonner"],
	["forsake", "forsook", "forsaken", "abandonner"],
	["freeze", "froze", "frozen", "geler"],
	["get", "got", "got", "obtenir"],
	["give", "gave", "given", "donner"],
	["go", "went", "gone", "aller"],
	["grow", "grew", "grown", "pousser"],
	["hang", "hung", "hung", "suspendre"],
	["have", "had", "had", "avoir"],
	["hear", "heard", "heard", "entendre"],
	["hide", "hid", "hidden", "cacher"],
	["hit", "hit", "hit", "frapper (3)"],
	["hold", "held", "held", "tenir"],
	["hurt", "hurt", "hurt", "blesser"],
	["keep", "kept", "kept", "garder"],
	["know", "knew", "known", "savoir"],
	["lay", "laid", "laid", "poser"],
	["lead", "led", "led", "mener"],
	["leap", "leapt", "leapt", "sauter"],
	["learn", "learnt", "learnt", "apprendre"],
	["leave", "left", "left", "laisser/quitter"],
	["lend", "lent", "lent", "prêter"],
	["let", "let", "let", "permettre/laisser"],
	["lie", "lay", "lain", "être couché"],
	["light", "lit", "lit", "éclairer"],
	["lose", "lost", "lost", "perdre"],
	["make", "made", "made", "faire (fabriquer)"],
	["mean", "meant", "meant", "signifier"],
	["meet", "met", "met", "rencontrer"],
	["pay", "paid", "paid", "payer"],
	["put", "put", "put", "mettre"],
	["read", "read", "read", "lire"],
	["ride", "rode", "ridden", "aller à vélo/cheval"],
	["ring", "rang", "rung", "sonner"],
	["rise", "rose", "risen", "s'élever"],
	["run", "ran", "run", "courrir"],
	["say", "said", "said", "dire (3)"],
	["see", "saw", "seen", "voir"],
	["sell", "sold", "sold", "vendre"],
	["send", "sent", "sent", "envoyer"],
	["shake", "shook", "shaken", "secouer"],
	["shine", "shone", "shone", "briller"],
	["shoot", "shot", "shot", "tirer (fusil)"],
	["show", "showed", "shown", "montrer"],
	["shut", "shut", "shut", "fermer"],
	["sing", "sang", "sung", "chanter"],
	["sink", "sank", "sunk", "s'enfoncer/couler"],
	["sit", "sat", "sat", "être assis"],
	["sleep", "slept", "slept", "dormir"],
	["smell", "smelt", "smelt", "sentir"],
	["speak", "spoke", "spoken", "parler"],
	["spell", "spelt", "spelt", "épeler"],
	["spend", "spent", "spent", "passer (temps)/dépenser"],
	["spill", "spilt", "spilt", "répandre (par mégarde)"],
	["split", "split", "split", "fendre"],
	["spoil", "spoilt", "spoilt", "gâter"],
	["spread", "spread", "spread", "répandre, étaler"],
	["spring", "sprang", "sprung", "bondir"],
	["stand", "stood", "stood", "être debout"],
	["stick", "stuck", "stuck", "coller"],
	["strike", "struck", "struck", "frapper (6)"],
	["swear", "swore", "sworn", "jurer"],
	["sweep", "swept", "swept", "balayer"],
	["swim", "swam", "swum", "nager"],
	["swing", "swung", "swung", "se balancer"],
	["take", "took", "taken", "prendre"],
	["teach", "taught", "taught", "enseigner"],
	["tear", "tore", "torn", "déchirer"],
	["tell", "told", "told", "dire (4)"],
	["think", "thought", "thought", "penser"],
	["throw", "threw", "thrown", "lancer"],
	["understand", "understood", "understood", "comprendre"],
	["wake", "woke", "woken", "(se) réveiller"],
	["wear", "wore", "worn", "porter (vêt°)"],
	["win", "won", "won", "gagner"],
	["write", "wrote", "written", "écrire"]
];